# Generated by Django 5.0.6 on 2024-05-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Servicios", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicio",
            options={"verbose_name": "servicio", "verbose_name_plural": "servicios"},
        ),
        migrations.AlterField(
            model_name="servicio",
            name="imagen",
            field=models.ImageField(upload_to="servicios"),
        ),
    ]
